---

- hosts: artifactory-allin1-ubuntu
  become: yes
  # vars: see -> ./group_vars/all/00_general.yml
  roles:
    - role: ansible-role-set-resolver
    - role: mariadb
    - role: oracle-java
      oracle_java_set_as_default: yes
    - role: artifactory
