---

- hosts: artifactory-ubuntu,artifactory-centos
  become: yes
  roles:
    - role: ansible-role-set-resolver
    - role: shelleg.epel
    - role: oracle-java
      oracle_java_set_as_default: yes
    - role: artifactory